
Reset root password			mysqld --init-file=C:\\Ashwini\\ElenVerve\\webproject\\TempElen\\SQL\\resetRootPass.txt
connect mysql				mysql -u root -p	
db changed					used mysql
INSERT INTO user (host, user, password, select_priv, insert_priv, update_priv) VALUES ('localhost', 'guest', PASSWORD('guest'), 'Y', 'Y', 'Y');

CREATE DATABASE ev;

CREATE TABLE USER_DTL (
		EMAIL_ID VARCHAR(25) NOT NULL,
		F_NAME VARCHAR(20),
		M_NAME VARCHAR(20),
		L_NAME VARCHAR(20) NOT NULL,
		GENDER VARCHAR(1),		
		PHONE  VARCHAR(15) 	,
		USER_VERIFIED INT,
		V_EMAIL_SENT_DATE DATE	,
		USER_TYPE INT,
	PRIMARY KEY (EMAIL_ID)		
);


CREATE TABLE USER_AUTH (  
	EMAIL_ID VARCHAR(20) NOT NULL,  
	PASSWORD VARCHAR(32) NOT NULL, 
	AUTHORITY VARCHAR(10) NOT NULL,  
	FOREIGN KEY (EMAIL_ID) REFERENCES USER_CREDT(EMAIL_ID)  
); 
	
CREATE TABLE ADDRESS_DTL(
		EMAIL_ID VARCHAR(20) NOT NULL,
		ADD_NAME VARCHAR(50),
		STREET_NUMBER VARCHAR(10),
		STREET_NAME VARCHAR(20),
		APT_NO VARCHAR(10),
		CITY VARCHAR(20),
		ZIP VARCHAR(15),
		COUNTRY VARCHAR(3),
		ADD_TYPE INT,
		FOREIGN KEY (EMAIL_ID) REFERENCES USER_DTL(EMAIL_ID) 
	)	;
	
CREATE TABLE FRD_CHK_DTL(
	EMAIL_ID VARCHAR(20) NOT NULL,
	IP_ADDRESS VARCHAR(24),	
	BRWS_CONFIG VARCHAR(255),
	LAST_LOGGED_IN_DT DATE,
	LAST_PURCHASED_DT DATE,
	LAST_LOGOUT_DT DATE,	
	FRD_ACC_FLG INT,
	LAT VARCHAR(20),
	LONGITUDE VARCHAR(20),
	COUNTRY VARCHAR(3),
	FOREIGN KEY (EMAIL_ID) REFERENCES USER_DTL(EMAIL_ID)
);

CREATE TABLE FRD_CHK_DTL_HS(
	EMAIL_ID VARCHAR(20) NOT NULL,
	IP_ADDRESS VARCHAR(24),	
	BRWS_CONFIG VARCHAR(255),
	LAST_LOGGED_IN_DT DATE,
	LAST_PURCHASED_DT DATE,
	LAST_LOGOUT_DT DATE,
	FRD_ACC_FLG INT,
	LAT VARCHAR(20),
	LONGITUDE VARCHAR(20),
	COUNTRY VARCHAR(3)
)
------------------------SHOPPING CART  -----------------------------------------
CREATE TABLE STATE_TAX(		
		STATE_NM VARCHAR(20),
		SALES_TAX_RATE VARCHAR(20)	
)

CREATE TABLE SHOPPING_CART_ITEMS(		
		SHOPPING_CART_ID VARCHAR(20),
		PRODUCT_ID VARCHAR(20),
		PRICE DECIMAL(5,5),
		SHOPPING_DATE DATE,
		USER_ID VARCHAR(20),
		QUANTITY INT	
)

CREATE TABLE ODRER_DETAILS(		
		ORDER_ID VARCHAR(20),
		USER_ID VARCHAR(20),
		RECEIVER_NAME VARCHAR(30),
		ADDRESS VARCHAR(50),
		CITY VARCHAR(20),
		ZIP VARCHAR(15),
		STATE VARCHAR(15),
		SHIPPING_TYPE VARCHAR(20),
		DT_PURCHASE	DATE	
)

CREATE TABLE SHIPPING_TYPE(		
		SHIPPING_TYPE VARCHAR(20),
		PRICE DECIMAL(5,5),
		APPRX_DAYS_DELIVERY INT				
)

CREATE TABLE PRODUCT_REVIEW(		
		PRODUCT_ID VARCHAR(20),
		REVIEWS VARCHAR(200),
		RATING INT	,
		REVIEW_DT DATE,
		USER_ID VARCHAR(20)		
)






